/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arras3888;

import java.awt.Color;

/**
 *
 * @author pedro
 */
public class Login extends javax.swing.JFrame {

       int xMouse, yMouse;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header_main = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        iniciar_sesion = new javax.swing.JLabel();
        usuario_txt = new javax.swing.JLabel();
        usuario_field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        password_Field = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        btn_login = new javax.swing.JPanel();
        boton_entrar = new javax.swing.JLabel();
        usuario_txt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(850, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(850, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_main.setBackground(new java.awt.Color(255, 255, 255));
        header_main.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_mainMouseDragged(evt);
            }
        });
        header_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_mainMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header_mainLayout = new javax.swing.GroupLayout(header_main);
        header_main.setLayout(header_mainLayout);
        header_mainLayout.setHorizontalGroup(
            header_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_mainLayout.createSequentialGroup()
                .addGap(0, 796, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_mainLayout.setVerticalGroup(
            header_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_mainLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(header_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/LOGIN.png"))); // NOI18N
        logo.setText("jLabel1");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 500));

        iniciar_sesion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        iniciar_sesion.setText("INICIAR SESION");
        jPanel1.add(iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        usuario_txt.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        usuario_txt.setText("Contraseña");
        jPanel1.add(usuario_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        usuario_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuario_field.setForeground(new java.awt.Color(204, 204, 204));
        usuario_field.setText("example@xubax.com");
        usuario_field.setBorder(null);
        usuario_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuario_fieldMousePressed(evt);
            }
        });
        usuario_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(usuario_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 440, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 440, -1));

        password_Field.setForeground(new java.awt.Color(204, 204, 204));
        password_Field.setText("********");
        password_Field.setToolTipText("");
        password_Field.setBorder(null);
        password_Field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                password_FieldMousePressed(evt);
            }
        });
        jPanel1.add(password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 440, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 440, -1));

        btn_login.setBackground(new java.awt.Color(0, 204, 204));

        boton_entrar.setBackground(new java.awt.Color(0, 102, 255));
        boton_entrar.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        boton_entrar.setForeground(new java.awt.Color(255, 255, 255));
        boton_entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_entrar.setText("Entrar");
        boton_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_entrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_entrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_entrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_loginLayout = new javax.swing.GroupLayout(btn_login);
        btn_login.setLayout(btn_loginLayout);
        btn_loginLayout.setHorizontalGroup(
            btn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_loginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(boton_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_loginLayout.setVerticalGroup(
            btn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_loginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(boton_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 120, 40));

        usuario_txt1.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        usuario_txt1.setText("Usuario");
        jPanel1.add(usuario_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuario_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_fieldActionPerformed

    private void header_mainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_mainMousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_header_mainMousePressed

    private void header_mainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_mainMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
        this.setLocation((x-xMouse),(y-yMouse));
    }//GEN-LAST:event_header_mainMouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exitBtn.setBackground(Color.red);
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exitBtn.setBackground(Color.white);
        exit.setForeground(Color.black);
    }//GEN-LAST:event_exitMouseExited

    private void boton_entrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_entrarMouseEntered
        // TODO add your handling code here:
        btn_login.setBackground(new Color(0,246,214));
    }//GEN-LAST:event_boton_entrarMouseEntered

    private void boton_entrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_entrarMouseExited
        btn_login.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_boton_entrarMouseExited

    private void usuario_fieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuario_fieldMousePressed
        if (usuario_field.getText().equals("example@xubax.com")) {
            usuario_field.setText("");
            usuario_field.setForeground(Color.black);
        }
        if (String.valueOf(password_Field.getPassword()).isEmpty()) {
            password_Field.setText("********");
            password_Field.setForeground(Color.gray);
        }
        

        
    }//GEN-LAST:event_usuario_fieldMousePressed

    private void password_FieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_FieldMousePressed
        if (usuario_field.getText().isEmpty()) {
            usuario_field.setText("example@xubax.com");
            usuario_field.setForeground(Color.gray); 
        }
        
         if (String.valueOf(password_Field.getPassword()).equals("********")) {
        password_Field.setText("");
        password_Field.setForeground(Color.black);
         }
    }//GEN-LAST:event_password_FieldMousePressed

    private void boton_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_entrarMouseClicked
        System.out.println("usuario: " + usuario_field.getText() + "\n contraseña: " + String.valueOf(password_Field.getPassword()));
    }//GEN-LAST:event_boton_entrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boton_entrar;
    private javax.swing.JPanel btn_login;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel header_main;
    private javax.swing.JLabel iniciar_sesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField password_Field;
    private javax.swing.JTextField usuario_field;
    private javax.swing.JLabel usuario_txt;
    private javax.swing.JLabel usuario_txt1;
    // End of variables declaration//GEN-END:variables
}
